#!/bin/sh
draw() {
  path="$(readlink -f -- "$1" | sed 's/\\/\\\\/g;s/"/\\"/g')"
  printf '{"action":"add","identifier":"preview","x":%d,"y":%d,"width":%d,"height":%d,"scaler":"contain","scaling_position_x":0.5,"scaling_position_y":0.5,"path":"%s"}\n' \
    "$x" "$y" "$width" "$height" "$path" >"$FIFO_UEBERZUG"
  exit 1
}

hash() {
  cache="$HOME/.cache/lf/$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f -- "$1")" | sha256sum | cut -d' ' -f1).jpg"
}

cache() {
  if ! [ -f "$cache" ]; then
    dir="$(dirname -- "$cache")"
    [ -d "$dir" ] || mkdir -p -- "$dir"
    "$@"
  fi
  draw "$cache"
}

file="$1"
width="$2"
height="$3"
x="$4"
y="$5"

case "$(file -Lb --mime-type -- "$file")" in
  image/*)
    if [ -p "$FIFO_UEBERZUG" ]; then
      # ueberzug doesn't handle image orientation correctly
      orientation="$(magick identify -format '%[orientation]\n' -- "$file[0]")"
      if [ -n "$orientation" ] \
          && [ "$orientation" != Undefined ] \
          && [ "$orientation" != TopLeft ]; then
        hash "$file"
        cache magick -- "$file[0]" -auto-orient "$cache"
      else
        draw "$file"
      fi
    fi
    ;;
  video/*)
    if [ -p "$FIFO_UEBERZUG" ]; then
      hash "$file"
      cache ffmpegthumbnailer -i "$file" -o "$cache" -s 0
    fi
    ;;
  application/pdf)
    if [ -p "$FIFO_UEBERZUG" ]; then
      hash "$file"
      cache pdftoppm -f 1 -singlefile -jpeg -- "$file" "${cache%.*}"
    fi
    ;;
  application/zip|application/x-tar|application/gzip|application/x-bzip2|application/x-xz|application/x-rar|application/x-7z-compressed)
    if command -v atool >/dev/null 2>&1; then
      exec atool -l -- "$file"
    elif command -v bsdtar >/dev/null 2>&1; then
      exec bsdtar -tf "$file"
    elif command -v unzip >/dev/null 2>&1 && file "$file" | grep -qi zip; then
      exec unzip -l "$file"
    elif command -v unrar >/dev/null 2>&1; then
      exec unrar l "$file"
    elif command -v 7z >/dev/null 2>&1; then
      exec 7z l "$file"
    else
      echo "No archive listing tool found"
    fi
    ;;
  *)
    exec bat --style=plain --color=always --paging=never "$file"
    ;;
esac

file -Lb -- "$file" | fold -s -w "$width"
exit 0
